-- node
-- should add new node (localhost:7845)
-- should remove existing node (localhost:7845)
-- should display gas price per unit
-- should state change on node change

-- account
-- should add new account
-- should export account with a password
-- should remove the account
-- should import with the exported one
-- should state change on account change
